import { Container } from '@mui/material';
import React, { useState, useEffect } from 'react'
import { Card, Row } from 'react-bootstrap';
import axios from 'axios';

export default function Home() {
    const user = axios.create({ baseURL: "http://localhost:8000" })
    const [data, setData] = useState({ totalInvoices: 0, pendingAmt: 0, totalAmtPaid: 0, totalAmt: 0, pendingInvoices: 0, list: [] });
    useEffect(async () => {
        //totainvoices
        await user.get(`/getInvoice/${JSON.parse(localStorage.getItem('credentials')).email}`).then(res => { data.totalInvoices = res.data.listLength; data.list = res.data.list; data.totalAmt = res.data.total });

        //totalinvoiceamt
        //totalinvoicepaid
        //totalinvoicepending
        await user.get(`/getPendingInvoice/${JSON.parse(localStorage.getItem('credentials')).email}`).then(res => { data.pendingInvoices = res.data.listLength; data.pendingAmt = res.data.total });
        setData({ ...data });
    }, [])
    return (
        <div>

            <Container className='my-5' >
                <Row className='d-flex justify-content-center align-items-center'>
                    <Card
                        bg="primary"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"

                    >
                        <Card.Header>Total Invoices Generated</Card.Header>
                        <Card.Body>
                            <Card.Title>{data.totalInvoices}</Card.Title>
                            <Card.Text>
                                Total no of Invoices Generated by User
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <Card
                        bg="dark"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"

                    >
                        <Card.Header>Total Amount Invoiced</Card.Header>
                        <Card.Body>
                            <Card.Title>{data.totalAmt}</Card.Title>
                            <Card.Text>
                                Total no of Invoice Amount
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <Card
                        bg="success"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"
                    >
                        <Card.Header>Total Amount Paid</Card.Header>
                        <Card.Body>
                            <Card.Title>{data.totalAmt - data.pendingAmt}</Card.Title>
                            <Card.Text>
                                Total no of Amount Paid by Customers
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <Card
                        bg="warning"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"
                    >
                        <Card.Header>Total Amount Pending</Card.Header>
                        <Card.Body>
                            <Card.Title>{data.pendingAmt}</Card.Title>
                            <Card.Text>
                                Total no of Amount Pending to be Paid by Customers
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <Card
                        bg="danger"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"
                    >
                        <Card.Header>Total Invoices Pending </Card.Header>
                        <Card.Body>
                            <Card.Title>{data.pendingInvoices}</Card.Title>
                            <Card.Text>
                                Total Invoices Cleared  By Customers
                            </Card.Text>
                        </Card.Body>
                    </Card>
                    <Card
                        bg="info"
                        text='white'
                        style={{ width: '18rem', height: '10rem' }}
                        className="m-5"
                    >
                        <Card.Header>Total Amount Invoices Cleared </Card.Header>
                        <Card.Body>
                            <Card.Title>{data.totalInvoices - data.pendingInvoices}</Card.Title>
                            <Card.Text>
                                Total Invoices Amount Cleared  By Customers
                            </Card.Text>
                        </Card.Body>
                    </Card>
                </Row>
            </Container>

        </div>
    )
}
